import os
from typing import Dict, Any, Optional

def get_loopers_autogen_config(
    loopers_key: str,
    proxy_url: str = "http://localhost:8080/v1",
    model: str = "gpt-4o",
    session_id: Optional[str] = None,
    extra_headers: Optional[Dict[str, str]] = None
) -> Dict[str, Any]:
    """
    Returns an AutoGen llm_config dictionary configured to route through the Loopers proxy.
    
    Args:
        loopers_key: The proxy key generated by `loopers keys create`.
        proxy_url: The URL to the Loopers proxy.
        model: The model string to request.
        session_id: Optional Loopers session ID to attach to this agent's calls.
        extra_headers: Additional headers to send.
        
    Returns:
        Dict: An llm_config dictionary ready to be passed to an AutoGen agent.
    """
    headers = extra_headers or {}
    if session_id:
        headers["X-Loopers-Session-ID"] = session_id
        
    return {
        "config_list": [
            {
                "model": model,
                "api_key": loopers_key,
                "base_url": proxy_url,
                "default_headers": headers
            }
        ]
    }
