import os
from typing import Optional
from langchain_openai import ChatOpenAI

def get_loopers_crewai_llm(
    loopers_key: str,
    proxy_url: str = "http://localhost:8080/v1",
    model: str = "gpt-4o",
    temperature: float = 0.7,
    max_tokens: Optional[int] = None,
    session_id: Optional[str] = None
) -> ChatOpenAI:
    """
    Returns a configured LLM suitable for use as a CrewAI agent's internal LLM.
    Under the hood, CrewAI uses LangChain, so we return a LangChain ChatOpenAI
    instance pointed at the Loopers proxy.
    
    Args:
        loopers_key: The proxy key generated by `loopers keys create`.
        proxy_url: The URL to the Loopers proxy.
        model: The model string to request.
        temperature: LLM temperature.
        max_tokens: Maximum tokens in response.
        session_id: Optional Loopers session ID to attach to this agent's calls.
        
    Returns:
        ChatOpenAI: A LangChain chat model.
    """
    default_headers = {}
    if session_id:
        default_headers["X-Loopers-Session-ID"] = session_id
        
    return ChatOpenAI(
        model=model,
        temperature=temperature,
        max_tokens=max_tokens,
        openai_api_key=loopers_key,
        openai_api_base=proxy_url,
        default_headers=default_headers if default_headers else None
    )
