[[IgnoredVulns]]
id = "GHSA-5p2g-fcmc-qvqq"
reason = "No fix available from Docusaurus; used only at build time."

[[IgnoredVulns]]
id = "GHSA-w3rx-r6r6-pgpr"
reason = "No fix available from Docusaurus; used only at build time."
